### ISSUE TITLE
[UPDATE] Build a News app using React.js, with i18n API in Strapi

### ISSUE THREAD

**Issue by Marktawa** [strapi/community-content#925]
**My update**

Hello 👋 

**Modifications**:  Make [this article](https://strapi.io/blog/build-a-news-app-using-react-js-with-i18n-api-in-strapi) Strapi v4 compatible.

### Task List
- [x] Initiate [project repo](https://github.com/Marktawa/newsapp)
- [x] Update article meta images
- [x] Create Dropbox paper draft
- [x] Update outline
- [x] Update prerequisites
- [x] Set up Strapi Backend
  - [x] Scaffold Strapi project
  - [x] Install Strapi i18n plugin
  - [x] Register Admin user
  - [x] Build Strapi collections
  - [x] Adding languages
  - [x] Seeding our database
  - [x] Let's add news content for French locale
  - [x] Open access to the News posts
- [x] Test Strapi Backend 
  - [x] Get all News posts
  - [x] Adding a news item
- [x] Set up React Frontend
  - [x] Scaffold React app
  - [x] Build the components
    - [x] Set up
    - [x] Header component
    - [x] NewsList component
    - [x] NewsView component
    - [x] NewsCard component
    - [x] AddNewsDialog component
  - [x] Add styling
- [x] Test app
- [x] Conclusion
- [x] Test repo
- [x] 1st Proofread
- [x] Grammarly Check
- [x] Hemmingwayapp Check
- [x] 2nd Proofread
- [x] Ready for Review

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by PaulBratslavsky** [comment]
@Marktawa are looking to update this article? If so, you can go ahead.  Just let me know when you get started.

**Comment by Marktawa** [comment]
@PaulBratslavsky 
I'm updating it.

**Comment by PaulBratslavsky** [comment]
@Marktawa nice 🙂

**Comment by Marktawa** [comment]
Hey @PaulBratslavsky 
I'm done. Here's the complete [draft](https://www.dropbox.com/scl/fi/j71rvj6br4ruyq97ep24e/Build-a-News-app-using-React.js-with-i18n-API-in-Strapi.paper?dl=0&rlkey=fhdf6ts6nx54efiz1d4gsljqg)
The article is ready for review.

**Comment by PaulBratslavsky** [comment]
@Marktawa thank you. @TiaraOluwanimi this article is ready for the next step.

**Comment by dessireugarte** [comment]
Hello @Marktawa  👋 
Your article is [live](https://strapi.io/blog/how-to-build-a-news-app-using-react-jsith-i18n-api-in-strapi)! 🎉
Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
Please feel free to reach out to me if you have any questions!
